import Head from 'next/head'
import Link from 'next/link'
import Footer from '../components/footer';
import Navbar from '../components/navbar'
import Dashboard from './dashboard';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div class="grid grid-cols-1 m-10 justify-items-center">
        <h1 class="sm:text-4xl md:text-5xl m-10  font-bold">Welcome to Decision Journal!</h1>
        <p class="sm:text-xl md:text-2xl m-10">Your personal decision ledger.</p>
        <Link href="/journal">
          <div class="flex space-x-2 justify-center border-black border-2 p-2">
            <p class="text-xl font-bold">Get Started</p>
            <img src="/back.png" width={36} height={36}></img>
          </div>
        </Link>
      </div>
      <p class="sm:text-xl md:text-2xl p-10 text-center">
        Decision Journal is a project for people willing to make in the world
        by their million dollar decision. 
        <span class="block"></span>It is designed to capture the process
        of your decision making
        <span class="block"></span> which you can use to make decisions in the
        future based on your previous decisions.
      </p>
      <Dashboard />
      <Footer />
    </div>
  );
}
